### ISSUE TITLE
VirusTotal scans

### ISSUE THREAD

**Issue by noobyme** [ShadowOxygen/OxygenX#14]
Hi I don't mean to accuse you of anything as I don't understand these things but why does virus total flag this as a trojan?
https://www.virustotal.com/gui/file/f6715a023490ca6ab119f6827c33dc697caee2f26a0ea95a13de070fb1e83fbb/behavior/VirusTotal%20Jujubox
https://www.virustotal.com/gui/file/36205472df8cfe6ad5bd740fa7aba7357430671ff1868a7451f2c5820c002451/relations

**Comment by ghost** [comment]
Use python version bro

**Comment by noobyme** [comment]
What you mean?

**Comment by noobyme** [comment]
I downloaded the exe from releases, then uploaded it to scan

**Comment by ShadowOxygen** [comment]
It detects as a trojan because it reads and uses the combolist on mojang's api
And also the first vt link that detected is a ratted version of OxygenX because thats not the results when I put my OxygenX
Original link is https://www.virustotal.com/gui/file/36205472df8cfe6ad5bd740fa7aba7357430671ff1868a7451f2c5820c002451/detection

not 
https://www.virustotal.com/gui/file/f6715a023490ca6ab119f6827c33dc697caee2f26a0ea95a13de070fb1e83fbb/behavior/VirusTotal%20Jujubox

**Comment by ShadowOxygen** [comment]
Also where did you get that version OxygenX? That is probably a ratted version since its bigger than mine

Please report it and remove it from your pc

**Comment by noobyme** [comment]
Oh OK thanks why does api detect as trojan tho just curious. Mb my 1st VT is linked to my 2nd VT under relations tab. So to reach the 1st link I posted, you go to relations tab on my second link and click the oxygen exe from execution parents

**Comment by noobyme** [comment]
Everything from right here lol which is why confuse

**Comment by noobyme** [comment]
How'd you see file size btw

**Comment by Happybooty** [comment]
Noob if you want you can attach the file you have onto a comment and I can check what the problem is.

**Comment by noobyme** [comment]
I've already deleted the exe from my computer lol, just wanted to get some more info on why all the red on VT. Thanks though, the conclusion right now I have is that the 1st VT link is just an unrelated ratted version of the exe that prob also shows up on the scan bc they have the same code so comes under execution parents or something. Can anyone reaffirm this? Also 1st time github user should I close this thread

**Comment by Happybooty** [comment]
Well I could've reaffirmed it with the exe but rip. I guess this is closed just wait for Shadow to see the conclusion.

**Comment by noobyme** [comment]
Maybe I can still find it somewhere, will have to check later though. I should clarify I only downloaded 1 file, and that was from github right here. There are 2 links I posted, the 2nd one I posted is the same as the one shadow did, my concern was mainly the 1st link I posted, which was found ON the virus total website as a relation.

**Comment by Happybooty** [comment]
Welp if you do find it tell me and I will check it to see if it is the same code as oxygenx or its a standalone because it is probably a ratted version of oxygenx which was detected by virus total as a relation as it contacts the same website (mojang auth server). If you do find it please attach it and I can check if it is this :)

**Comment by ShadowOxygen** [comment]
So your question on 1st VT detecting OxygenX as a trojan because it reads your combolist and sends a payload to the api (Exactly the way trojan works but OxygenX only send payload to mojang's api and does not steal your file/stuff/hits) 

Hope this helps

**Comment by noobyme** [comment]
Sorry are you referring to my this https://www.virustotal.com/gui/file/36205472df8cfe6ad5bd740fa7aba7357430671ff1868a7451f2c5820c002451/relations
