### ISSUE TITLE
(Quick Question)

### ISSUE THREAD

**Issue by delorn** [ShadowOxygen/OxygenX#44]
This is a fully working checker that doesn't miss hits right? I've checked alot of combos so far and gotten no hits. But I do love the speed of this checker, It's Awesome!

**Comment by ghost** [comment]
Ur hits depend on if you proxies are good. I have bought private proxies and i got way more hits from a combo i already checked with public proxies

**Comment by delorn** [comment]
Yeah, That makes sense since there would be no one or alot less people using the proxies

**Comment by ShadowOxygen** [comment]
So far, I can not find any thing in my code that skip hits. 
If your using public proxies, you will get more bad accounts since the proxies are banned (Basically Mojang's api blocks the ip from authenticating, so any requests made by a banned ip will return as a bad account which have nothing to do with OxygenX)

**Comment by delorn** [comment]
Oh, I get it sorry.
