### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ezchazumm** [ShadowOxygen/OxygenX#58]
I open the checker, import combos and proxies. Then it says starting threads and changes pages, and the checker just doesn't start

**Comment by ShadowOxygen** [comment]
First, make sure your using the exe otherwise if your using the python script, make sure to download the requirements. 
Second, check the settings file to make sure your using the proxies and timeouts.
Third, if you use all the steps above and it still doesn't work, turn on debug mode and let me know the errors.
